# Generated by Django 6.1.1 on 2026-09-26 11:17

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('row_status', models.SmallIntegerField(choices=[(0, 'Активная'), (1, 'Изменённая'), (2, 'Удалена')], db_index=True, default=0, verbose_name='Статус записи')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Введите номер в международном формате, например +77001234567.', regex='^\\+[1-9]\\d{7,14}$')], verbose_name='Номер телефона')),
                ('timezone', models.CharField(default='Asia/Almaty', max_length=64, verbose_name='Часовой пояс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ('organization__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('row_status', models.SmallIntegerField(choices=[(0, 'Активная'), (1, 'Изменённая'), (2, 'Удалена')], db_index=True, default=0, verbose_name='Статус записи')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('row_status', models.SmallIntegerField(choices=[(0, 'Активная'), (1, 'Изменённая'), (2, 'Удалена')], db_index=True, default=0, verbose_name='Статус записи')),
                ('name', models.CharField(max_length=100, verbose_name='Название организации')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Введите номер в международном формате, например +77001234567.', regex='^\\+[1-9]\\d{7,14}$')], verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('avatar', models.ImageField(blank=True, upload_to='organization_photos/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('working_days', models.CharField(blank=True, max_length=255, verbose_name='Рабочие дни')),
                ('timezone', models.CharField(default='Asia/Almaty', max_length=64, verbose_name='Часовой пояс')),
                ('currency', models.CharField(default='KZT', max_length=3, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ('name',),
            },
        ),
    ]
