import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("organizations", "0003_subscription_and_photos"),
        ("services", "0002_seed_service_categories"),
        ("staff", "0003_staff_title_staffprofession_staff_professions_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(name="Campaign", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Идентификатор")),
            ("create_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")), ("update_date", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")), ("row_status", models.SmallIntegerField(choices=[(0,"Активная"),(1,"Изменённая"),(2,"Удалена")], db_index=True, default=0, verbose_name="Статус записи")),
            ("title", models.CharField(max_length=160, verbose_name="Название")), ("message", models.TextField(verbose_name="Сообщение")), ("photo", models.ImageField(blank=True, upload_to="campaigns/", verbose_name="Изображение")), ("recipients", models.JSONField(default=list, verbose_name="Получатели")), ("status", models.CharField(choices=[("draft","Черновик"),("queued","В очереди"),("sent","Отправлена"),("failed","Ошибка")], default="draft", max_length=10, verbose_name="Статус")), ("total_recipients", models.PositiveIntegerField(default=0, verbose_name="Получателей")), ("success_count", models.PositiveIntegerField(default=0, verbose_name="Доставлено")),
            ("created_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL, verbose_name="Кто создал")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="campaigns", to="organizations.organization")), ("updated_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL, verbose_name="Кто изменил")),
        ], options={"ordering": ("-create_date",)}),
        migrations.CreateModel(name="Client", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Идентификатор")), ("create_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")), ("update_date", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")), ("row_status", models.SmallIntegerField(choices=[(0,"Активная"),(1,"Изменённая"),(2,"Удалена")], db_index=True, default=0, verbose_name="Статус записи")),
            ("first_name", models.CharField(max_length=80, verbose_name="Имя")), ("last_name", models.CharField(blank=True, max_length=80, verbose_name="Фамилия")), ("middle_name", models.CharField(blank=True, max_length=80, verbose_name="Отчество")), ("phone_number", models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Введите номер в международном формате, например +77001234567.", regex="^\\+[1-9]\\d{7,14}$")], verbose_name="Телефон")), ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")), ("birthday", models.DateField(blank=True, null=True, verbose_name="Дата рождения")), ("gender", models.CharField(blank=True, choices=[("male","Мужской"),("female","Женский")], max_length=10, verbose_name="Пол")), ("status", models.CharField(choices=[("basic","Обычный"),("vip","VIP"),("blocked","Заблокирован")], default="basic", max_length=10, verbose_name="Статус")), ("discount_percent", models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name="Скидка, %")), ("height_cm", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Рост, см")), ("weight_kg", models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="Вес, кг")), ("note", models.TextField(blank=True, verbose_name="Заметка")), ("photo", models.ImageField(blank=True, upload_to="client_photos/", verbose_name="Фото")),
            ("created_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL, verbose_name="Кто создал")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="clients", to="organizations.organization")), ("updated_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL, verbose_name="Кто изменил")),
        ], options={"ordering": ("last_name", "first_name")}),
        migrations.CreateModel(name="Deal", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Идентификатор")), ("create_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")), ("update_date", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")), ("row_status", models.SmallIntegerField(choices=[(0,"Активная"),(1,"Изменённая"),(2,"Удалена")], db_index=True, default=0, verbose_name="Статус записи")),
            ("status", models.CharField(choices=[("open","Открыта"),("paid","Оплачена"),("cancelled","Отменена")], default="open", max_length=12, verbose_name="Статус")), ("total", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Сумма")), ("discount", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Скидка")), ("payment_date", models.DateTimeField(blank=True, null=True, verbose_name="Дата оплаты")), ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
            ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deals", to="organizations.branch")), ("client", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deals", to="operations.client")), ("created_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL, verbose_name="Кто создал")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deals", to="organizations.organization")), ("updated_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL, verbose_name="Кто изменил")),
        ]),
        migrations.CreateModel(name="Appointment", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Идентификатор")), ("create_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")), ("update_date", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")), ("row_status", models.SmallIntegerField(choices=[(0,"Активная"),(1,"Изменённая"),(2,"Удалена")], db_index=True, default=0, verbose_name="Статус записи")),
            ("starts_at", models.DateTimeField(verbose_name="Начало")), ("ends_at", models.DateTimeField(verbose_name="Окончание")), ("price", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Цена")), ("status", models.CharField(choices=[("pending","Ожидает"),("confirmed","Подтверждена"),("completed","Завершена"),("cancelled","Отменена"),("no_show","Не пришёл")], default="pending", max_length=12, verbose_name="Статус")), ("source", models.CharField(choices=[("crm","CRM"),("online","Онлайн"),("phone","Телефон")], default="crm", max_length=10, verbose_name="Источник")), ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
            ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="appointments", to="organizations.branch")), ("created_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL, verbose_name="Кто создал")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="organizations.organization")), ("service", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="appointments", to="services.service")), ("specialist", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="appointments", to="staff.staff")), ("updated_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL, verbose_name="Кто изменил")), ("client", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="appointments", to="operations.client")), ("deal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="appointments", to="operations.deal")),
        ], options={"ordering": ("starts_at",)}),
        migrations.CreateModel(name="LoyaltyProgram", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Идентификатор")), ("create_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")), ("update_date", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")), ("row_status", models.SmallIntegerField(choices=[(0,"Активная"),(1,"Изменённая"),(2,"Удалена")], db_index=True, default=0, verbose_name="Статус записи")),
            ("kind", models.CharField(choices=[("bonus","Бонусная карта"),("subscription","Абонемент"),("certificate","Сертификат")], max_length=16, verbose_name="Тип")), ("name", models.CharField(max_length=120, verbose_name="Название")), ("price", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Цена")), ("reward_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Бонус, %")), ("initial_balance", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Начальный баланс")), ("visits_count", models.PositiveIntegerField(blank=True, null=True, verbose_name="Количество посещений")), ("validity_days", models.PositiveIntegerField(blank=True, null=True, verbose_name="Срок, дней")), ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
            ("created_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL, verbose_name="Кто создал")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="loyalty_programs", to="organizations.organization")), ("services", models.ManyToManyField(blank=True, related_name="loyalty_programs", to="services.service")), ("updated_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL, verbose_name="Кто изменил")),
        ], options={"ordering": ("kind", "name")}),
        migrations.CreateModel(name="ClientLoyalty", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Идентификатор")), ("create_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")), ("update_date", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")), ("row_status", models.SmallIntegerField(choices=[(0,"Активная"),(1,"Изменённая"),(2,"Удалена")], db_index=True, default=0, verbose_name="Статус записи")), ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Баланс")), ("remaining_visits", models.PositiveIntegerField(blank=True, null=True, verbose_name="Осталось посещений")), ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="Действует до")), ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="loyalty_accounts", to="operations.client")), ("created_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL, verbose_name="Кто создал")), ("updated_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL, verbose_name="Кто изменил")), ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="client_accounts", to="operations.loyaltyprogram")),
        ]),
        migrations.CreateModel(name="PaymentMethod", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Идентификатор")), ("create_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")), ("update_date", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")), ("row_status", models.SmallIntegerField(choices=[(0,"Активная"),(1,"Изменённая"),(2,"Удалена")], db_index=True, default=0, verbose_name="Статус записи")), ("name", models.CharField(max_length=100, verbose_name="Название")), ("commission", models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0"))], verbose_name="Комиссия")), ("commission_type", models.CharField(choices=[("percent","Процент"),("fixed","Фиксированная")], default="percent", max_length=10, verbose_name="Тип комиссии")), ("is_active", models.BooleanField(default=True, verbose_name="Активен")), ("created_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL, verbose_name="Кто создал")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_methods", to="organizations.organization")), ("updated_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL, verbose_name="Кто изменил")),
        ], options={"ordering": ("name",)}),
        migrations.AddField(model_name="loyaltyprogram", name="excluded_payment_methods", field=models.ManyToManyField(blank=True, related_name="excluded_loyalty_programs", to="operations.paymentmethod")),
        migrations.AddField(model_name="deal", name="payment_method", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="deals", to="operations.paymentmethod")),
        migrations.CreateModel(name="Bill", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Идентификатор")), ("create_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")), ("update_date", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")), ("row_status", models.SmallIntegerField(choices=[(0,"Активная"),(1,"Изменённая"),(2,"Удалена")], db_index=True, default=0, verbose_name="Статус записи")), ("name", models.CharField(max_length=120, verbose_name="Название")), ("amount", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0"))], verbose_name="Сумма")), ("description", models.TextField(blank=True, verbose_name="Описание")), ("bill_type", models.CharField(choices=[("income","Доход"),("expense","Расход")], max_length=10, verbose_name="Тип")), ("created_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL, verbose_name="Кто создал")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bills", to="organizations.organization")), ("updated_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL, verbose_name="Кто изменил")), ("payment_methods", models.ManyToManyField(blank=True, related_name="bills", to="operations.paymentmethod")),
        ], options={"ordering": ("-create_date",)}),
        migrations.AddConstraint(model_name="client", constraint=models.UniqueConstraint(fields=("organization","phone_number"), name="client_phone_per_organization")),
        migrations.AddIndex(model_name="appointment", index=models.Index(fields=["organization","starts_at"], name="operations__organiz_d2eb6a_idx")),
        migrations.AddIndex(model_name="appointment", index=models.Index(fields=["specialist","starts_at"], name="operations__special_199289_idx")),
        migrations.AddConstraint(model_name="clientloyalty", constraint=models.UniqueConstraint(fields=("client","program"), name="client_loyalty_program_unique")),
        migrations.AddConstraint(model_name="paymentmethod", constraint=models.UniqueConstraint(fields=("organization","name"), name="payment_method_name_per_organization")),
    ]
