# Generated by Django 6.1.1 on 2026-09-22 11:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5)], verbose_name='Длительность, минуты')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('currency', models.CharField(default='KZT', max_length=3, verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='specialists.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Услуга специалиста',
                'verbose_name_plural': 'Услуги специалистов',
                'ordering': ('name', 'specialist__last_name'),
                'constraints': [models.UniqueConstraint(fields=('specialist', 'name'), name='unique_service_name_per_specialist')],
            },
        ),
    ]
