# Generated by Django 6.1.1 on 2026-09-26 11:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('staff', '0003_staff_title_staffprofession_staff_professions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('row_status', models.SmallIntegerField(choices=[(0, 'Активная'), (1, 'Изменённая'), (2, 'Удалена')], db_index=True, default=0, verbose_name='Статус записи')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок в списке')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('row_status', models.SmallIntegerField(choices=[(0, 'Активная'), (1, 'Изменённая'), (2, 'Удалена')], db_index=True, default=0, verbose_name='Статус записи')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5)], verbose_name='Длительность, мин')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, help_text='Заполните, если цена «от … до». Пусто — фиксированная цена.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена до')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите, чтобы временно убрать услугу, не удаляя её.', verbose_name='Доступна для записи')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='organizations.organization', verbose_name='Организация')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('category__position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('row_status', models.SmallIntegerField(choices=[(0, 'Активная'), (1, 'Изменённая'), (2, 'Удалена')], db_index=True, default=0, verbose_name='Статус записи')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Своя длительность, мин')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Своя цена')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Своя цена до')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='services.service', verbose_name='Услуга')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='staff.staff', verbose_name='Мастер')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Услуга мастера',
                'verbose_name_plural': 'Услуги мастеров',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='services', through='services.StaffService', to='staff.staff', verbose_name='Мастера'),
        ),
        migrations.AddConstraint(
            model_name='staffservice',
            constraint=models.UniqueConstraint(fields=('staff', 'service'), name='staff_service_unique'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(condition=models.Q(('row_status', 2), _negated=True), fields=('organization', 'name'), name='service_unique_name_in_organization'),
        ),
    ]
