# Generated by Django 6.1.1 on 2026-09-22 11:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='Должность')),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Введите номер в международном формате, например +77001234567.', regex='^$|^\\+[1-9]\\d{7,14}$')], verbose_name='Телефон')),
                ('photo_url', models.URLField(blank=True, verbose_name='Ссылка на фото')),
                ('bio', models.TextField(blank=True, verbose_name='О специалисте')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='organizations.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='SpecialistCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('image_url', models.URLField(verbose_name='Ссылка на изображение')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='specialists.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='Выходной')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Окончание')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Окончание перерыва')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='specialists.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'График работы',
                'ordering': ('weekday',),
                'constraints': [models.UniqueConstraint(fields=('specialist', 'weekday'), name='unique_specialist_weekday')],
            },
        ),
    ]
