export type AppSection =
  | 'dashboard'
  | 'journal'
  | 'clients'
  | 'campaigns'
  | 'specialists'
  | 'services'
  | 'loyalty'
  | 'finance'
  | 'analytics'
  | 'tutorial'
  | 'support'
  | 'settings'
