# Generated by Django 6.1.1 on 2026-09-26 11:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('row_status', models.SmallIntegerField(choices=[(0, 'Активная'), (1, 'Изменённая'), (2, 'Удалена')], db_index=True, default=0, verbose_name='Статус записи')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Введите номер в международном формате, например +77001234567.', regex='^\\+[1-9]\\d{7,14}$')], verbose_name='Номер телефона')),
                ('career_start_date', models.DateField(blank=True, null=True, verbose_name='Начало карьеры')),
                ('bio', models.TextField(blank=True, verbose_name='О специалисте')),
                ('photo', models.ImageField(blank=True, upload_to='staff_photos/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите, если сотрудник уволен или не работает. Удаление — это row_status.', verbose_name='Работает')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='organizations.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('surname', 'name'),
            },
        ),
    ]
