# Generated by Django 6.1.1 on 2026-09-26 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
        ('staff', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.CharField(blank=True, help_text='Своё название: «Топ-стилист», «Старший мастер». Профессии — из справочника.', max_length=100, verbose_name='Должность в салоне'),
        ),
        migrations.CreateModel(
            name='StaffProfession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('row_status', models.SmallIntegerField(choices=[(0, 'Активная'), (1, 'Изменённая'), (2, 'Удалена')], db_index=True, default=0, verbose_name='Статус записи')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основная')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_links', to='professions.profession', verbose_name='Профессия')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_professions', to='staff.staff', verbose_name='Сотрудник')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Профессия сотрудника',
                'verbose_name_plural': 'Профессии сотрудников',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='professions',
            field=models.ManyToManyField(blank=True, related_name='staff', through='staff.StaffProfession', to='professions.profession', verbose_name='Профессии'),
        ),
        migrations.AddConstraint(
            model_name='staffprofession',
            constraint=models.UniqueConstraint(fields=('staff', 'profession'), name='staff_profession_unique'),
        ),
        migrations.AddConstraint(
            model_name='staffprofession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('staff',), name='staff_single_primary_profession'),
        ),
    ]
