# Generated by Django 6.1.1 on 2026-09-26 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0003_staff_title_staffprofession_staff_professions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('row_status', models.SmallIntegerField(choices=[(0, 'Активная'), (1, 'Изменённая'), (2, 'Удалена')], db_index=True, default=0, verbose_name='Статус записи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_working', models.BooleanField(default=True, verbose_name='Рабочий день')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='staff.staff', verbose_name='Сотрудник')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'День графика',
                'verbose_name_plural': 'График по дням',
                'ordering': ('staff', 'date'),
            },
        ),
        migrations.CreateModel(
            name='DailyWorkingInterval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('row_status', models.SmallIntegerField(choices=[(0, 'Активная'), (1, 'Изменённая'), (2, 'Удалена')], db_index=True, default=0, verbose_name='Статус записи')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(verbose_name='Конец работы')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('daily_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_intervals', to='work_schedule.dailyschedule', verbose_name='День графика')),
                ('updated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Рабочий интервал',
                'verbose_name_plural': 'Рабочие интервалы',
                'ordering': ('daily_schedule', 'start_time'),
            },
        ),
        migrations.AddConstraint(
            model_name='dailyschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('row_status', 2), _negated=True), fields=('staff', 'date'), name='daily_schedule_unique_staff_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyworkinginterval',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='working_interval_end_after_start'),
        ),
    ]
